services:
  supplier-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "supplier"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
#    volumes:
#      - supplier-data:/var/lib/postgresql/data
  supplier-app:
    build: ./supplier
    ports:
      - "8080:8080"
    depends_on:
      - supplier-db
  consumer-app:
    build: ./consumer
    ports:
      - "8081:8081"
volumes:
  supplier-data: